##
## EPITECH PROJECT, 2021
## CPPool_Epitech_Tech2
## File description:
## Makefile
##

all:
		make -C Ex00/
		make -C Ex01/
		make -C Ex02/

clean:
		make clean -C Ex00/
		make clean -C Ex01/
		make clean -C Ex02/


fclean:
		make fclean -C Ex00/
		make fclean -C Ex01/
		make fclean -C Ex02/

re:		fclean	all

.PHONY:		all clean fclean re