##
## EPITECH PROJECT, 2021
## CPPool_Epitech_Tech2
## File description:
## Makefile
##

all:
		make -C Morning/

clean:
		make clean -C Morning/

fclean:
		make fclean -C Morning/

re:		fclean	all

.PHONY:		all clean fclean re