##
## EPITECH PROJECT, 2021
## CPPool_Epitech_Tech2
## File description:
## Makefile
##

all:
		make -C Ex00/

clean:
		make clean -C Ex00/

fclean:
		make fclean -C Ex00/

re:		fclean	all

.PHONY:		all clean fclean re