##
## EPITECH PROJECT, 2021
## CPPool_Epitech_Tech2
## File description:
## Makefile
##

all:
		make -C Ex00/
		make -C Ex01/
		make -C Ex02/
		make -C Ex03/

clean:
		make clean -C Ex00/
		make clean -C Ex01/
		make clean -C Ex02/
		make clean -C Ex03/

fclean:
		make fclean -C Ex00/
		make fclean -C Ex01/
		make fclean -C Ex02/
		make fclean -C Ex03/

re:		fclean	all

.PHONY:		all clean fclean re