name: Create GitHub Release

on:
  push:
    branches:
      - master

jobs:
  Create_GitHub_release:
    runs-on: ubuntu-latest

    steps:
    - name: Create release for me
      uses: actions/create-release@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.event.client_payload.ReleaseBranchName }}
        release_name: ${{ github.event.client_payload.ReleaseBranchName }}
        body: ${{ github.event.client_payload.ReleaseBody }}
        prerelease:
        commitish: ${{ github.event.client_payload.Commitish }}